name: Check for Framework Updates

on:
  schedule:
    # Run weekly on Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main
    paths:
      - 'framework-mapping.json'
      - '.github/workflows/check-updates.yml'

jobs:
  check-updates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq rsync

      - name: Clone WooCommerce repository
        run: |
          git clone --bare https://github.com/woocommerce/woocommerce.git .tmp-wc

      - name: Check for changes in each framework version
        id: check_changes
        run: |
          chmod +x bin/check-framework-changes.sh
          ./bin/check-framework-changes.sh

      - name: Create or update versions if changes detected
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          chmod +x bin/generate-versions.sh
          ./bin/generate-versions.sh

      - name: Determine versions with changes
        id: changed_versions
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          # Get list of changed versions from the check script output
          CHANGED=$(cat .changed-versions.txt 2>/dev/null || echo "")
          echo "changed_versions=${CHANGED}" >> $GITHUB_OUTPUT
          echo "Changed versions: ${CHANGED}"

      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update framework versions: ${{ steps.changed_versions.outputs.changed_versions }}"
          title: "Framework Update: ${{ steps.changed_versions.outputs.changed_versions }}"
          body: |
            ## Framework Update Detected

            This PR updates the WooCommerce PHPUnit framework files.

            ### Changed Versions
            ${{ steps.changed_versions.outputs.changed_versions }}

            ### Details
            - Source: WooCommerce official repository
            - Timestamp: ${{ github.event.head_commit.timestamp }}
            - Triggered by: ${{ github.event_name }}

            ### Review Checklist
            - [ ] Verify extracted files are correct
            - [ ] Check for any breaking changes
            - [ ] Update CHANGELOG.md if needed

            This PR was automatically created by the framework update workflow.
          branch: framework-update-${{ github.run_number }}
          delete-branch: true
          labels: |
            automated
            framework-update

      - name: Clean up
        if: always()
        run: |
          rm -rf .tmp-wc
          rm -f .changed-versions.txt
